name: Sync Private Repository to Public Repository

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull changes from private repository
        run: |
          git pull origin main
          git  config --global user.email "edwin.sany@taotesting.com"
          git config --global user.name "Edwin Focaloid"          
          git checkout -b public-version
          git status 
          ls -al 
          git branch 
          git rm -r infra
          git rm -r docker 
          git rm -r remove.txt
          ls -al
          git add * 
          git commit -m "fix: testing"                       

      - name: Push changes to public repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          repository: git@github.com:oat-sa/test-public1-repo.git
          branch: develop
          force: true
