name: release-public-version
on:

  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs: 
  build: 
    name: setup public repository 
    runs-on: ubuntu-latest

    steps:

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Clone remote repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      

      - name: setup users
        run: | 
          git  config --global user.email "edwin.sany@taotesting.com"
          git config --global user.name "Edwin Focaloid"
          
          time=$(date +"%I-%M-%S_%d-%m-%Y")
          git checkout -b "public-$time"
          git branch
          git status 
          ls -al 

      - name: remove secret files 
        run: |
          git rm -r infra
          git rm -r docker 
          git rm -r remove.txt
          git rm -r .github/workflows/push-changes-to-public.yml
          git add * 
          git commit -m "fix: testing"

      - name: push to public repository 
        run: |
          
          git remote add public git@github.com:oat-sa/test-public1-repo.git
          git remote -v
          branch_name=$(git branch  | grep '*' | awk '{print $2}')
          #git push -u public "$branch_name":"$branch_name"
          git push -u public "$branch_name":develop --force
  
